### ISSUE TITLE
drawerPosition attribute not the same as in android implementation

### ISSUE THREAD

**Issue by DanielMSchmidt** [iodine/react-native-drawer-layout#11]
Hi there,

First of all thanks for the great lib!
I just wanted to inform you, that the drawerPosition seems to need other parameters in the ios implementation, than in the android implementation. While calling it with `'left'` or `'right'` in the ios, rather than  `DrawerLayoutAndroid.positions.Left` in the android implementation.

If this is intended I would suggest to add a notice in the documentation.

Kind regards!

**Comment by dbanck** [comment]
The following error occurs when using something like `drawerPosition="right"` on Android:

![screenshot_20151204-182229](https://cloud.githubusercontent.com/assets/45985/11596260/4d7f7348-9ab4-11e5-936e-1e22ad8232e1.png)

**Comment by DanielMSchmidt** [comment]
@dbanck, sorry I completely forgot about this issue. I guess as the goal of this component is to have an iOS Polyfill the best way to get rid of this error should be to refer to the RN documentation. I will try to do so and file a pull request soon, hopefully tomorrow.

**Comment by mfmendiola** [comment]
Fixed here: https://github.com/iodine/react-native-drawer-layout/pull/23
