### ISSUE TITLE
Enable/Disable drawer

### ISSUE THREAD

**Issue by JonnyBGod** [iodine/react-native-drawer-layout#13]
This would be helpful to enable simpler structures for navigation.

It would enable to use a drawer as a parent component to a router and easily enable/disable depending on the route.

**Comment by DanielMSchmidt** [comment]
Wouldn't this be an issue to be filed in react native itself, as this is only an iOS Polyfill for the DrawerLayoutAndroid?

**Comment by mfmendiola** [comment]
@DanielMSchmidt Agreed.  The functionality simply mirrors what's made available for `DrawerLayoutAndroid`.
