### ISSUE TITLE
Unexpected token?

### ISSUE THREAD

**Issue by dangnelson** [iodine/react-native-drawer-layout#22]
I copied and pasted the example from the docs and got the following error:

```
node_modules/react-native-drawer-layout/DrawerLayout.ios.js: Unexpected token (15:22)
```

Does this have to do with Babel options? Not sure how that works.

**Comment by mfmendiola** [comment]
If you copied and pasted the code to your own project, then yes, I suspect this may have to do with your babel options. Do you have a `.babelrc` file defined at the root of your react-native project? If so, you need to add `es7.decorators`, `es7.classProperties`, `es6.modules`, `es6.constants`, and `es6.blockScoping` to the `whitelist` of your `.babelrc` file. See the example's `.babelrc` here: https://github.com/iodine/react-native-drawer-layout/blob/master/DrawerLayoutExample/.babelrc.  

Note: https://github.com/iodine/react-native-drawer-layout/pull/21 will remove the need to do this.

**Comment by dangnelson** [comment]
Any estimate on when #21 will be merged? I've been trying to avoid es6/es7 😊

**Comment by onchainguy-btc** [comment]
Also need a merge of #21 
Running into https://github.com/facebook/react-native/issues/4690

**Comment by DanielMSchmidt** [comment]
#21 Just merge, I think @mfmendiola said he would make the 0.3 release as soon as this is done, so it should be out soon :+1:
