### ISSUE TITLE
Basic test

### ISSUE THREAD

**Issue by DanielMSchmidt** [iodine/react-native-drawer-layout#24]
Hi there,

As this lib grows I would like to get your opinion on writing tests for it. To my mind especially tests which give us some safety against the current spec would be great, maybe even some kind of tooling to test it against different versions of react-native. 

I searched for projects which also provide a component and have tests and found [RefreshableListView
](https://github.com/jsdf/react-native-refreshable-listview). They use jest for unit tests, we may also use it for e.g. having the callbacks triggered or keyboard closed. The problem with "copying" this approach would be that they don't really render the component (as far as I can understand the tests), so testing if the component mounts successfully isn't really an option. 

If you have any ideas how to do some kind of integration tests, please share. If you would like to have at first at least the unit tests (and maybe the linting) let me know, I was already looking forward to learn this and it would be a great opportunity to me ;)

Have a nice day!

**Comment by mfmendiola** [comment]
Having some jest unit tests + linting (with something lie http://eslint.org/ and flow) and setting them up as part of a continuous integration process would be a great start.  Given the small size/scope of this component, I'm not too worried about having UI integration tests, but if we do, we should look into a service that supports both Android and iOS.  Something like http://appium.io/ may work nicely.

**Comment by DanielMSchmidt** [comment]
I agree with you, integration tests shouldn't be necessary. 

I just looked in our not integration test options for a CI and found [Circle CI](https://circleci.com/) which seems to be pretty awesome. Tried it out for my upcoming PR and it just worked out of the box, I just had to signup and add the project (my fork, someone of your company would have to do this for the main project). I guess we get a status badge and a test badge for upcoming PRs for free, which is pretty great!

**Comment by DanielMSchmidt** [comment]
Hi there, just wanted to give you a short update: I've been trying to add tests the last couple days and, in fact, I ended up copying the approach of  [the snowflake app](https://github.com/bartonhammond/snowflake), but even though it currently doesn't work, even with basic tests. That said, if you didn't open an account for circle ci yet, we may also look into [Bitrise.io](https://www.bitrise.io/). The snowflake app uses them and they seem to be pleased with their service (full android and ios test support)

**Comment by mfmendiola** [comment]
@DanielMSchmidt Sorry for the delay.  Am looking into setting it up right now.  I've also added you as a contributor on npm.

**Comment by DanielMSchmidt** [comment]
Thanks a lot!

**Comment by DanielMSchmidt** [comment]
Just to keep you up to date:

I had some small successes getting to run jest within the project. Unfortunately, I am having problems getting the shallow rendering to work in my feature branch: https://github.com/DanielMSchmidt/react-native-drawer-layout/tree/feature/unit-tests

The error I get is `Invariant Violation: ReactShallowRenderer render(): Invalid component element. Instead of passing a component class, make sure to instantiate it by passing it to React.createElement.` and I am not quite sure what it tries to tell me :smile: 

I am hoping to get some insights from examining the [snowflake app](https://github.com/bartonhammond/snowflake) and I will ask a question either on StackOverflow or the React Native Facebook group. If any of you has experiences with testing in react native I would be glad to get a little hint ;)

**Comment by DanielMSchmidt** [comment]
Moved to react-native-community/react-native-drawer-layout#1
