### ISSUE TITLE
Unknown module "dismissKeyboard"

### ISSUE THREAD

**Issue by khadorkin** [iodine/react-native-drawer-layout#26]
Exist in v.0.3.0

![RN](https://www.evernote.com/shard/s263/sh/d897da34-32bb-4cb4-bc2c-94cebb86fe9a/505baa1f5e2f6d59/res/b278971a-4e54-4efd-80a5-cb76d6ae6dad/skitch.png?resizeSmall&width=832)

**Comment by andreipt** [comment]
Reproducible for me too on v0.3.0

**Comment by mfmendiola** [comment]
@DanielMSchmidt

**Comment by mfmendiola** [comment]
@khadorkin @andreipt What do your environments look like (e.g. React Native version, npm version, node version)?

**Comment by williamrijksen** [comment]
Same issue here, environment:
Version: 0.3.0
React native version: 0.17
npm: 2.14.15
node: v5.3.0

**Comment by DanielMSchmidt** [comment]
Well, I don't really get why, [it is still there](https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Libraries/Utilities/dismissKeyboard.js) and it is [similary used](https://github.com/facebook/react-native/blob/0e8b207cc34f230eb2cced3981734b522b601817/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js#L22) within RN but I will try to reproduce it and to find the bug

**Comment by DanielMSchmidt** [comment]
Yes, it can be reproduced on my system too.

**Comment by DanielMSchmidt** [comment]
I just opened a bugfix, not great, but should work for now. I hope they expose all packages through the default export of react native soon, sothat we don't have to rely on paths anymore...

**Comment by mayusha** [comment]
Hi.

Have the same issue. Was it fixed?

**Comment by DanielMSchmidt** [comment]
@mayusha The Pull Request is not merged yet, once it is this problem should be fixed.

**Comment by mayusha** [comment]
@DanielMSchmidt Ok, thanks. I am looking forward to the merge.

**Comment by yongxiaofeng** [comment]
Sorry to bring it back, still having same issue within Xcode. 
Version: 0.3.1
react-native: 0.1.8
node v5.4.0
npm: 2.14.15

![screen shot 2016-01-10 at 3 49 01 am](https://cloud.githubusercontent.com/assets/213419/12220769/2bbf411a-b74d-11e5-8946-d5e319b17c3d.png)
