### ISSUE TITLE
Invalid directory '/Users/node_modules/autobind-decorator'

### ISSUE THREAD

**Issue by williamrijksen** [iodine/react-native-drawer-layout#27]
I ran into the following issue when building in Xcode.

```
uncaught error Error: UnableToResolveError: Unable to resolve module autobind-decorator from /Users/williamrijksen/MyApp/node_modules/react-native-drawer-layout/dist/DrawerLayout.ios.js: Invalid directory /Users/node_modules/autobind-decorator
```

Please help.

Version: 0.3.0
React native version: 0.17
npm: 2.14.15
node: v5.3.0

**Comment by andreipt** [comment]
I get the same error, but not when building in Xcode. I get it while running the app on the iPhone simulator.

Version: 0.3.0
React native version: 0.15.0
npm: 3.5.2
node: v5.0.0

**Comment by mfmendiola** [comment]
Hmm seems like `autobind-decorator` needs to be added as a dependency.  https://github.com/iodine/react-native-drawer-layout/commit/66128da9bcca99793f7427502de207c6bdc2ea16 should fix this.

**Comment by williamrijksen** [comment]
@mfmendiola Thanks, that fixes this issue! But now i ran into the dismissKeyboard error, earlier reported at https://github.com/iodine/react-native-drawer-layout/issues/26.

`UnableToResolveError: Unable to resolve module dismissKeyboard`
