### ISSUE TITLE
Unable to download JS bundle

### ISSUE THREAD

**Issue by avishayil** [iodine/react-native-drawer-layout#32]
Hi,

I can't seem to download JS bundle when requiring this package.
I thought in the beginning something is wrong with my setup, but them I tried to require it on another project and it seems that the packager is stuck always at 99% when downloading the bundle.

Any solutions?

**Comment by arshsingh** [comment]
It's probably a babel transformation error. This should be fixed with https://github.com/iodine/react-native-drawer-layout/commit/761d899fc80187d2cf8cb08a633d9beb2f0a6c68

**Comment by browniefed** [comment]
Would be great to get this published with the babel fix

**Comment by DanielMSchmidt** [comment]
@avishayil Can you test if the bug still occurs in the latest version?

**Comment by DanielMSchmidt** [comment]
May this be a duplicate of #37 ?

**Comment by browniefed** [comment]
The reason is the current published version still includes whitelist in package.json causing Babel 6 issues

**Comment by DanielMSchmidt** [comment]
No, 0.3.4 has no whitelist option in the package.json, it is the same one as currently on the master brach.

**Comment by browniefed** [comment]
Ah good, I'll check in the morning, .3.4 wasn't published when I was testing

**Comment by DanielMSchmidt** [comment]
@browniefed Hey, do you have feedback for me? I would love to get rid of the last bug issue :+1:

**Comment by browniefed** [comment]
Everything looks good, thanks!

**Comment by DanielMSchmidt** [comment]
Awesome!
