### ISSUE TITLE
Unable to resolve module dismissKeyboard

### ISSUE THREAD

**Issue by notlose** [iodine/react-native-drawer-layout#37]
not working on both android and ios 
Unable to download JS bundle after require('react-native-drawer-layout');

**Comment by DanielMSchmidt** [comment]
Thanks for the feedback! I currently have a bugfix in development, but I hadn't had enough time to test it yet. I hope I will get this to work at the weekend, will keep you up to date.

**Comment by DanielMSchmidt** [comment]
Should be fixed in v0.3.3, @notlose can you verify?

**Comment by andythink** [comment]
@DanielMSchmidt I also have encountered this problem, I can help verify this problem together

**Comment by Thomas101** [comment]
we also found this problem in 0.3.3

**Comment by DanielMSchmidt** [comment]
Okay, first of all the obvious question: which bife and react-native version do you use? It would be great if one of you could check out this repo and start the Example, so I know if that works for you pr even better, if one of you could add a link to a failing example or
how I can reproduce this error.  
My problem is, I tested this code on two computers and it worked

**Comment by andythink** [comment]
I update to 0.3.4, now it can work normal. @DanielMSchmidt

**Comment by DanielMSchmidt** [comment]
Okay, I will close this issue. If anyone still encounters it and can tell me how to reproduce it I will reopen this issue ;)
