### ISSUE TITLE
Overlay is not rendered on ios when drawer is shown

### ISSUE THREAD

**Issue by andreo** [iodine/react-native-drawer-layout#46]
On ios, when you drag a drawer - an overlay is not rendered and not dimmed. We should change this code in the render method: `const drawerShown = openValue > 0;`, since `openValue` is an `AnimatedValue`, there is no way to synchronously read its value because it might be driven natively. As a result `drawerShown` is always false and overlay is not rendered.

This problem exists on react-native 0.18.1

**Comment by DanielMSchmidt** [comment]
Hey, Thanks for your issue I will investigate the problem soon. Just to be sure I understand you right, you say there is no overlay rendered as you start dragging?

**Comment by andreo** [comment]
> you say there is no overlay rendered as you start dragging?

Yes, this block is never rendered:

```
        {drawerShown &&
          <TouchableWithoutFeedback onPress={this._onOverlayClick}>
            <Animated.View
              style={[styles.overlay, animatedOverlayStyles]} />
          </TouchableWithoutFeedback>
        }
```

**Comment by JonnyBGod** [comment]
+1

**Comment by DanielMSchmidt** [comment]
Sorry for the delay, I just merged your PR, thanks for your help!
