### ISSUE TITLE
Overlay still here !

### ISSUE THREAD

**Issue by slamus** [iodine/react-native-drawer-layout#49]
Hello,

I saw the issue was fixed in #44, but I still have the overlay in front of my children and cannot touch through it...

My code :

``` jsx
<DrawerLayout
        drawerWidth={UIStyle.MENU_WIDTH}
        drawerPosition={DrawerLayout.positions.Left}
        renderNavigationView={()=>{
          return <UIMenu router={this.props.router}/>
        }}
        ref={(c)=>this._DrawerLayout = c}
      >
        {React.Children.map(this.props.children, c => React.cloneElement(c, {
          route: this.props.route
        }))}
        {this.getNavbar()}
      </DrawerLayout>
```

**Comment by DanielMSchmidt** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible! It may have been reintroduced in #46, although I am quite sure I checked it before I merged. Nevertheless, I will have a look at it over the weekend. If you need a solution even earlier, I would be glad to see a PR on that topic ;) Have a nice day!

**Comment by slamus** [comment]
Thanks for your feedback !
But sorry it was on my end :(
Used position absolute for the UIMenu component...

**Comment by DanielMSchmidt** [comment]
Hey, thanks for letting me know. Good Luck with your application!
