### ISSUE TITLE
InteractionManager.runAfterInteractions is never called when using this package

### ISSUE THREAD

**Issue by bcalik** [iodine/react-native-drawer-layout#50]
I use [InteractionManager.runAfterInteractions](https://facebook.github.io/react-native/docs/interactionmanager.html) while doing heavy operations.

It allows long-running work to be scheduled after any interactions/animations have completed. In particular, this allows JavaScript animations to run smoothly.

The problem is when I use drawer-layout package, runAfterInteractions callback is never called.

**Comment by bcalik** [comment]
I tried removing this part of the code from `DrawerLayout.ios.js` and everything is working well now.

``` javascript
      if (value === 0 || value === 1) {
        if (this.interactionHandle) {
          InteractionManager.clearInteractionHandle(this.interactionHandle);
        }
      } else {
        this.interactionHandle = InteractionManager.createInteractionHandle();
      }
```

**Comment by DanielMSchmidt** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible!

**Comment by DanielMSchmidt** [comment]
Hey, Sorry for the delay, I only found time now to look at this problem. I found the problem (basically an infinite amount of created interaction handles) in the code part you have mentioned and fixed it in a local branch. I will test it once more and publish it in the next version.

**Comment by faceyspacey** [comment]
I also can never get `runAfterInteractions` to work. I use `create/ClearInterationHandle` and that seems to work. I run create it before animations and clear it after, and animations are noticeably smoother. But `runAfterInteractions` never gets called for me, and I've tried many times over the last 2 months. 

Also, is there an inverse operation? i.e. run after renderings?  I.e. to run animations and guarantee it runs after renderings.
