### ISSUE TITLE
Missing drawerLockMode prop

### ISSUE THREAD

**Issue by mauricesvay** [iodine/react-native-drawer-layout#52]
https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#content

DrawerLayoutAndroid now has a `drawerLockMode` prop that specifies if the drawer should be locked or not. This prop is missing from `react-native-drawer-layout`.

**Comment by DanielMSchmidt** [comment]
Thanks for mentioning this, if you like to do a pull request or need any help with this do not hesitate to ask. Otherwise I will try to come up with something in the next couple of weeks.

**Comment by mauricesvay** [comment]
I've made a PR for that. However there is a behavior difference for unspecified behaviors. Let me know what you think about that.

**Comment by DanielMSchmidt** [comment]
@mauricesvay Thank you a lot for you PR, it is part of version 0.5.0. I doing exactly what the docs state is the best possible outcome of this component, so yeah, awesome work.

**Comment by mauricesvay** [comment]
Awesome! Thanks for making this module :)
