### ISSUE TITLE
Does not seem to work on iOS !

### ISSUE THREAD

**Issue by saumya** [iodine/react-native-drawer-layout#59]
I just created a basic react-native project and try to add react-native-drawer from npm and git both. But as soon as I require it. The application comes up with the Red screen.

I have not tried it on Android yet.

**Comment by DanielMSchmidt** [comment]
Hi, thanks for your feedback. 
Could you please provide the following information:
- react-native version
- react-native-drawer-layout version
- your code (the component where you use react-native-drawer-layout)
- the exact error message

Thanks a lot!

**Comment by saumya** [comment]
Its a basic React Native init project.
[https://github.com/saumya/HelloRnDot23](https://github.com/saumya/HelloRnDot23)

>   "react": "^0.14.8",
>   "react-native": "^0.23.0",
>   "react-native-drawer-layout": "^0.5.0"

**Comment by saumya** [comment]
Well, got this working by changing 

> import {DrawerLayout} from 'react-native-drawer-layout';

to

> var DrawerLayout = require('react-native-drawer-layout');

Thanks

**Comment by DanielMSchmidt** [comment]
I see the problem with your original import: 
You would need to do `ìmport DrawerLayout from 'react-native-drawer-layout'`` rather than deconstruct the exported component. I will include a small paragraph in the readme, thanks for your feedback!

**Comment by saumya** [comment]
Thanks a lot @DanielMSchmidt . That solution got it working.
