### ISSUE TITLE
Errors while compiling for a real iOS device

### ISSUE THREAD

**Issue by duketwo** [iodine/react-native-drawer-layout#62]
Compiling works when using the Simulator but not when compiling for a real device.
Buildscheme: Debug/Release
React native version: 0.23
Tried clearing the node_modules already, also createad a blank project with just the dependency import.

`
    /bin/sh -c /Users/bader/Library/Developer/Xcode/DerivedData/react_native_eventmanager-fjbowjhkawswazcogmppfquvoxtz/Build/Intermediates/react_native_eventmanager.build/Debug-iphoneos/react_native_eventmanager.build/Script-00DD1BFF1BD5951E006B06BC.sh
- DEST=/Users/bader/Library/Developer/Xcode/DerivedData/react_native_eventmanager-fjbowjhkawswazcogmppfquvoxtz/Build/Products/Debug-iphoneos/react_native_eventmanager.app
- node /Users/bader/Projects/react_native_eventmanager/node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/bader/Library/Developer/Xcode/DerivedData/react_native_eventmanager-fjbowjhkawswazcogmppfquvoxtz/Build/Products/Debug-iphoneos/react_native_eventmanager.app/main.jsbundle --assets-dest /Users/bader/Library/Developer/Xcode/DerivedData/react_native_eventmanager-fjbowjhkawswazcogmppfquvoxtz/Build/Products/Debug-iphoneos/react_native_eventmanager.app
  bundle: Created ReactPackager
  uncaught error Error: UnableToResolveError: Unable to resolve module ./DrawerLayout.android from /Users/bader/Projects/react_native_eventmanager/node_modules/react-native-drawer-layout/dist/index.js: Unable to find this module in its module map or any of the node_modules directories under /Users/bader/Projects/react_native_eventmanager/node_modules/react-native-drawer-layout/dist/DrawerLayout.android and its parent directories

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
   at /Users/bader/Projects/react_native_eventmanager/node_modules/node-haste/lib/DependencyGraph/ResolutionRequest.js:470:17
   at run (/Users/bader/Projects/react_native_eventmanager/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
   at /Users/bader/Projects/react_native_eventmanager/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
   at flush (/Users/bader/Projects/react_native_eventmanager/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:14:5)
   at _combinedTickCallback (node.js:370:9)
   at process._tickCallback (node.js:401:11)
   See logs /var/folders/k5/hyqw8v8541v4c886dt6dqfy40000gp/T/react-packager.log
   at SocketClient._handleMessage (SocketClient.js:144:23)
   at BunserBuf.<anonymous> (SocketClient.js:53:42)
   at emitOne (events.js:90:13)
   at BunserBuf.emit (events.js:182:7)
   at BunserBuf.process (/Users/bader/Projects/react_native_eventmanager/node_modules/bser/index.js:289:10)
   at /Users/bader/Projects/react_native_eventmanager/node_modules/bser/index.js:244:12
   at _combinedTickCallback (node.js:370:9)
   at process._tickCallback (node.js:401:11)
   Command /bin/sh failed with exit code 1`

**Comment by duketwo** [comment]
Don't know why it fails, but here is a temp workaround:

[index.js]
var React = require('react-native');
var Platform = React.Platform;
var ios = require('./DrawerLayout.ios').default;
var _reactNative = require('react-native');

if (Platform.OS === 'android') {
  module.exports = _reactNative.DrawerLayoutAndroid;
}

if (Platform.OS === 'ios') {
  module.exports = ios;
}

**Comment by DanielMSchmidt** [comment]
Thank you for your time, I will try to find the bug the next couple of days. If you find out more, please share your information and if you come to the conclusion, that this is a real bug of this library you are invited to open a PR 👍

**Comment by dimitriwalters** [comment]
All `require` statements are executed, even in a conditional block. The workaround above works because it is not using `require` for the android drawer

**Comment by DanielMSchmidt** [comment]
Well okay, thanks for your input, seems reasonable. maybe the react native guys broke the direct require statement. I will use the temporary fix and file a PR later today.

**Comment by duketwo** [comment]
Do you have an idea why it behaves differently when compiling for the simulator/real device?

**Comment by DanielMSchmidt** [comment]
honestly no, but I could imagine that the public interface of react native may be restricted when requesting without a dev flag, but this is just guessing. hopefully I can tell you more after fixing this issue

**Comment by DanielMSchmidt** [comment]
@duketwo @dimitriwalters Does anyone of you happen to have the time to check out my [PR](https://github.com/DanielMSchmidt/react-native-drawer-layout/tree/bugfix/require-fails)? I have no android setup on my current machine and it would save me a lot of time :)

**Comment by dimitriwalters** [comment]
Yeah I could do it, I'll be able to look at it tomorrow afternoon if you don't get to it by then

**Comment by DanielMSchmidt** [comment]
Yay, that is awesome, thanks a lot!

**Comment by dimitriwalters** [comment]
Ugh nevermind, I can't install your branch for some reason. I guess using npm is more complicated than I thought, sorry :(

**Comment by DanielMSchmidt** [comment]
@dimitriwalters I just uploaded it to my [dropbox](https://www.dropbox.com/s/83mtxbcxcnsngm7/react-native-drawer-layout.zip?dl=0) You would be needed to do the following:
1. download & unarchive the content of the zip (dist folder and package.json)
2. remove the content of `your_project_path/node_modules/react-native-drawer-layout` and put the items above in there
3. See if it works for android and send me the result

I would be so glad if you could do this. Otherwise I would most likely have to find someone who may borrow me an android phone, this may take a while

**Comment by dimitriwalters** [comment]
Just tested, it works :)

**Comment by DanielMSchmidt** [comment]
Awesome, thanks a lot for your help!

**Comment by DanielMSchmidt** [comment]
Fix is included in version 0.5.1
