### ISSUE TITLE
The drawer is shown default and can't be closed in ios

### ISSUE THREAD

**Issue by feyy** [iodine/react-native-drawer-layout#65]
react-native: 0.24.1

**Comment by DanielMSchmidt** [comment]
Hey,

Thanks for your feedback, would you mind showing your code, so that we may reproduce it easily? Bonus points for a Github project I may check out. The more detail you provide the faster I may tackle this bug ;)

**Comment by feyy** [comment]
Sorry, It's my fault to set the wrong property! So It's because I didn't set the drawerWidth property!

Thanks for your reply!

**Comment by DanielMSchmidt** [comment]
No problem, please don't hesitate if you have any more questions 👍
