### ISSUE TITLE
Android Platform:  Settings property drawerPosition error

### ISSUE THREAD

**Issue by naivehhr** [iodine/react-native-drawer-layout#69]
This problem only occurs in the android platform

"react": "^15.1.0",
"react-native": "^0.27.2",
"react-native-drawer-layout": "^1.0.0",

![2016-07-02 01 28 51 pm](https://cloud.githubusercontent.com/assets/5243456/16538552/5e557540-405a-11e6-92ee-0a9054c94895.png)
![2016-07-02 01 38 28 pm](https://cloud.githubusercontent.com/assets/5243456/16538553/5e730952-405a-11e6-8964-bb77cf1e0cec.png)

**Comment by DanielMSchmidt** [comment]
The problem you have is that the API changed, you have to use 

``` jsx
<DrawerLayout
  ..
  drawerPosition={DrawerLayout.positions.Left}
/>
```

This library uses a version, which works with both notations.

**Comment by naivehhr** [comment]
Ok, thank you!!
