### ISSUE TITLE
How am  suppose to use this

### ISSUE THREAD

**Issue by affibox** [iodine/react-native-drawer-layout#71]
I have no idea how this works. you guys need to do better ar documenting how people can use this

**Comment by DanielMSchmidt** [comment]
Sorry that you feel this way, but we have clearly stated, that this library is just a polyfill for [ DrawerLayoutAndroid](https://facebook.github.io/react-native/docs/drawerlayoutandroid.html). Therefore the usage is the same as described by facebook (except that we don't have the Android suffix). I hope this helps you, if you have any further questions, please don't hesitate to ask.
