### ISSUE TITLE
Anyway to get drawer status?like opened(opening)/closed(closeing)?

### ISSUE THREAD

**Issue by dyguests** [iodine/react-native-drawer-layout#72]
Hi,it's a very good component for both android and ios.

And,is anyway to get the drawer is open or close?

I also saw API of DrawerLayoutAndroid,but I don't find that.

:)

**Comment by DanielMSchmidt** [comment]
As you already said we use the API of the `DrawerLayoutAndroid` component. As far as I know they don't provide an option for that, so you would need to track it on your own with the `onDrawerOpen` and `onDrawerClose` callbacks.

**Comment by dyguests** [comment]
Got it.

```
<DrawerLayout

onDrawerOpen={()=> {
    this.isOpened = true;
    this.isClosed = false;
}}
onDrawerClose={()=> {
    this.isOpened = false;
    this.isClosed = true;
}}
/>
```

```

    toggleDrawer = ()=> {
        console.log('openDrawer');
        if (this.isClosed) {
            this.isClosed = false;
            this.drawerLayout.openDrawer();
        } else if (this.isOpened) {
            this.isOpened = false;
            this.drawerLayout.closeDrawer();
        }
    };
```

**Comment by DanielMSchmidt** [comment]
Even simpler, saving `isOpen` would be enough as if it is not open it is closed, there is no other state.

**Comment by dyguests** [comment]
really???

But I think there is 4 states. opened/opening/closed/closing.

With your way,maybe this happen:
  1.call openDrawer when isClosing.
  2.call closeDrawer when isOpening.

**Comment by DanielMSchmidt** [comment]
Yeah, you are right, totally forgot about the transitioning states.
