### ISSUE TITLE
Add Background image for Side Menu

### ISSUE THREAD

**Issue by ignivaankushrishi** [iodine/react-native-drawer-layout#73]
How can I add a background image in the drawer, I want to add menu options with their icons?

**Comment by DanielMSchmidt** [comment]
As to be seen in the [documentation](http://facebook.github.io/react-native/releases/0.30/docs/drawerlayoutandroid.html#drawerlayoutandroid), you may render everything you like in the `renderNavigationView` callback. If you would like to do a background image, you may see [this guide](http://facebook.github.io/react-native/releases/0.30/docs/images.html#background-image-via-nesting)
