### ISSUE TITLE
Changing the background color of the overlay?

### ISSUE THREAD

**Issue by nodegin** [iodine/react-native-drawer-layout#74]
Hello, is it possible to changing the background color of the overlay, for example `#fff`?

**Comment by DanielMSchmidt** [comment]
Hi,

Yes it is, please see the [doumentation of the polyfilled component](http://facebook.github.io/react-native/releases/0.31/docs/drawerlayoutandroid.html#drawerbackgroundcolor). Thanks for pointing this out, I just realized that we were missing this property, so I added it for version 1.1.0.

Hope this helps you, if you have any further questions, please don't hesitate to ask.

**Comment by nodegin** [comment]
@DanielMSchmidt Yes I tried this, but seems it's changing the background color of the drawer, but I'm looking for the overlay

**Comment by DanielMSchmidt** [comment]
Oh, you mean the overlay. If I see that correctly there is no option to do that in the original implementation, so I see no chance of including this here. But this would be only one line to change, so I have to suggest that you do a fork. ([This is the line](https://github.com/iodine/react-native-drawer-layout/blob/master/src/DrawerLayout.ios.js#L342)). I would be much happier to include this feature, but I like to stay with the original implementation.
