### ISSUE TITLE
Default to cross-platform solution

### ISSUE THREAD

**Issue by joewood** [iodine/react-native-drawer-layout#76]
This component works for **react-native-windows**. Could you check the test in `index.js` to default to using DrawLayout.ios.js rather than the `else if`?

``` javascript
if (Platform.OS === 'android') {
  module.exports = DrawerLayoutAndroid;
} else {
  module.exports = require('./DrawerLayout.ios').default;
}
```

In fact, i think the package will do this for you if you just have one file called `index.android.js` and another `index.js`.

**Comment by DanielMSchmidt** [comment]
Hey, thanks for reaching out. Haven't thought about this use case yet, and I will try both alternatives, the later one seems, even more, error resistant. 

If you could spare the time, could you contribute an example application similar to the ones listed under examples, e.g. [this one](https://github.com/DanielMSchmidt/DrawerLayoutExample) for react-native-windows? This would help me to keep the compatibility with this platform in mind.

**Comment by ericvicenti** [comment]
I agree this is pretty important. I've submitted a PR for it here:

https://github.com/iodine/react-native-drawer-layout/pull/80

**Comment by DanielMSchmidt** [comment]
Merged the PR. Having a working example would be great. I would be so happy if anyone could provide that :)
