### ISSUE TITLE
ListView not rendering inside the drawer

### ISSUE THREAD

**Issue by MohsinTariq10** [iodine/react-native-drawer-layout#78]
I am trying to display a listview inside the drawer but the problem is it does not display the list at first but when you click somewhere the are the listview appears magically :D

**Comment by MohsinTariq10** [comment]
Weird I got it working by setting the 'removeClippedSubviews'  to {false}. 
Found the solution here :
https://github.com/facebook/react-native/issues/1831

**Comment by DanielMSchmidt** [comment]
hey, thanks for your feedback! could you provide a minimal example so that I can test your solution?

**Comment by DanielMSchmidt** [comment]
Close due to missing feedback
