### ISSUE TITLE
open/close functions on iOS DrawerLayout should match those of Android DrawerLayout

### ISSUE THREAD

**Issue by mfmendiola** [iodine/react-native-drawer-layout#8]
The current iOS version defines `open` and `close`, while Android defines `openDrawer` and `closeDrawer`.  See: https://github.com/facebook/react-native/blob/master/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js#L179

**Comment by brentvatne** [comment]
This is in now with #10 :sunglasses: 

@mfmendiola - can you test it out and publish to npm when you're happy with it?

**Comment by mfmendiola** [comment]
sure :smile:
