### ISSUE TITLE
Joining react-native-community organisation

### ISSUE THREAD

**Issue by knowbody** [iodine/react-native-drawer-layout#81]
Hey folks, I'd like to say a big thank you for the project and for maintaining it.

We'd love to have you at react-native-community https://github.com/react-native-community!
We started the org so it's easier for others to find great and well maintained projects. And also to take a bit of load of you in terms of maintaining the project. Let us know if you'd like to join.

**Comment by satya164** [comment]
Also we're using the library in https://github.com/react-community/react-navigation, so being able to collaborate will be awesome!

**Comment by DanielMSchmidt** [comment]
@knowbody Sounds nice, let's do it! You can write me a mail to danielmschmidt92@gmail.com ;)

**Comment by knowbody** [comment]
I added you to the organisation! 🎉
that's awesome

**Comment by DanielMSchmidt** [comment]
I think @mfmendiola or someone at iodine needs to do the relocation, as I don't have the settings tab available here to move the project. Will message them later and keep you up to date

**Comment by knowbody** [comment]
thank you!
