### ISSUE TITLE
Tap on overlay does not close drawer

### ISSUE THREAD

**Issue by daveols** [iodine/react-native-drawer-layout#82]
As per the title: in my implementation, tapping on the overlay does not close the drawer as expected. The drawer is "unlocked" so it should have definitely fired the close function. 

I put a console log in the `_overlayClick` function locally to see if it fires at all and it doesn't. Can anyone help?

**Comment by DanielMSchmidt** [comment]
Moved it to the new repository:  react-native-community/react-native-drawer-layout#2
